// #429 scope item 2 — the committed JSON-Schema snapshots and the gate on them.
//
// The staleness block is the gate: committed bytes vs freshly generated bytes,
// per module. It reds on a narrowing the frozen corpora structurally cannot see
// (an enum member no stream picks, an optional field no seed sets), and the CI
// step in .github/workflows/ci.yml runs the same regenerate and requires
// `git status --porcelain` to come back empty.
//
// The blocks around it prove the properties the gate depends on: the rendering
// is deterministic (or the CI gate would red at random), and the failure
// message names what moved (or "not equal" on 4 KB of JSON tells a reviewer
// nothing).
import { describe, expect, it } from "vitest";
import { builtinModules } from "../sports/index.ts";
import { goldenPath } from "./golden.ts";
import {
  buildSchemaSnapshot,
  collapseKeysFor,
  formatSnapshotChanges,
  readSnapshotText,
  renderSchemaSnapshot,
  snapshotChanges,
  snapshotPath,
  stalenessReport,
  statePathKinds,
} from "./schema-snapshot.ts";
import type { SchemaSnapshot } from "./schema-snapshot.ts";

// Building every snapshot walks eleven corpora, one of which is 1.8 MB. Done
// once and shared: vitest's 5 s default kills a per-test rebuild of cricket and
// renders it as a bare STACK_TRACE_ERROR, which reads like an assertion failure
// and is not one.
const SNAPSHOTS = new Map<string, SchemaSnapshot>(
  builtinModules.map((module) => [module.key, buildSchemaSnapshot(module)]),
);

function snapshotFor(key: string): SchemaSnapshot {
  const hit = SNAPSHOTS.get(key);
  if (hit === undefined) throw new Error(`no snapshot built for "${key}"`);
  return hit;
}

describe("schema snapshot — staleness gate", () => {
  it("covers every builtin module", () => {
    expect(builtinModules.length).toBe(11);
  });

  for (const module of builtinModules) {
    it(`${module.key} — the committed snapshot matches the live schemas`, () => {
      const fresh = renderSchemaSnapshot(snapshotFor(module.key));
      const committed = readSnapshotText(module.key);
      // The report IS the assertion: an equal-bytes run reports "", and a stale
      // one reports which section moved and what moved in it.
      expect(stalenessReport(module.key, committed, fresh)).toBe("");
    });
  }

  it("puts each snapshot next to the corpus it complements", () => {
    for (const module of builtinModules) {
      expect(snapshotPath(module.key)).toBe(goldenPath(module.key).replace(".golden.json", ".schema.json"));
    }
  });

  it("records the module version, pinned at 1.0.0 for all eleven", () => {
    for (const module of builtinModules) {
      const snapshot = snapshotFor(module.key);
      expect(snapshot.version).toBe(module.version);
      expect(snapshot.version).toBe("1.0.0");
    }
  });
});

describe("schema snapshot — what it actually captures", () => {
  it("captures config enum members no golden stream has to exercise", () => {
    // The claim the whole pass rests on: the schema half is taken from the
    // DECLARATION, so it is complete whether or not a stream picked the member.
    const football = snapshotFor("football");
    const rendered = JSON.stringify(football.configSchema);
    expect(rendered).toContain("properties");
    expect(rendered.length).toBeGreaterThan(200);
  });

  it("captures the event payload union", () => {
    for (const module of builtinModules) {
      expect(snapshotFor(module.key).eventSchema).toBeTypeOf("object");
    }
  });

  it("captures state paths with their JSON kinds", () => {
    for (const module of builtinModules) {
      const paths = snapshotFor(module.key).state.paths;
      expect(Object.keys(paths).length).toBeGreaterThan(0);
      for (const kinds of Object.values(paths)) {
        expect(kinds.length).toBeGreaterThan(0);
        expect([...kinds].sort()).toEqual(kinds);
      }
    }
  });

  it("excludes the module's config from the state paths — the config half owns it", () => {
    // Every builtin files its parsed config under `cfg`; `configStateKey`
    // locates it by identity rather than by that spelling.
    for (const module of builtinModules) {
      const paths = Object.keys(snapshotFor(module.key).state.paths);
      expect(paths.filter((p) => p === "cfg" || p.startsWith("cfg."))).toEqual([]);
    }
  });
});

describe("state walk", () => {
  const lineups = {
    home: { entrantId: "H", slots: [{ personId: "p1", slot: "starting" as const, orderNo: 1 }] },
    away: { entrantId: "A", slots: [{ personId: "p2", slot: "starting" as const, orderNo: 1 }] },
  };

  it("collapses the side keys and every lineup id", () => {
    const collapse = collapseKeysFor(lineups);
    expect([...collapse].sort()).toEqual(["A", "H", "away", "home", "p1", "p2"]);
  });

  it("renders a person-keyed record as `[]`, not as 22 id-named paths", () => {
    const kinds = statePathKinds(
      { runs: { p1: 12, p2: 0 }, note: "x" },
      collapseKeysFor(lineups),
      new Set(),
    );
    expect([...kinds.keys()].sort()).toEqual(["note", "runs", "runs[]"]);
    expect([...(kinds.get("runs[]") ?? [])]).toEqual(["number"]);
  });

  it("records the KIND at every path, including array leaves", () => {
    const kinds = statePathKinds(
      { periods: [{ minutes: 45, ended: false }], tags: ["a"], missing: null },
      new Set(),
      new Set(),
    );
    expect([...(kinds.get("periods") ?? [])]).toEqual(["array"]);
    expect([...(kinds.get("periods[]") ?? [])]).toEqual(["object"]);
    expect([...(kinds.get("periods[].minutes") ?? [])]).toEqual(["number"]);
    expect([...(kinds.get("periods[].ended") ?? [])]).toEqual(["boolean"]);
    expect([...(kinds.get("tags[]") ?? [])]).toEqual(["string"]);
    expect([...(kinds.get("missing") ?? [])]).toEqual(["null"]);
  });

  it("widens a path that carried two kinds across states", () => {
    const collapse = new Set<string>();
    const kinds = statePathKinds({ winner: null }, collapse, new Set());
    statePathKinds({ winner: "H" }, collapse, new Set(), kinds);
    expect([...(kinds.get("winner") ?? [])].sort()).toEqual(["null", "string"]);
  });

  it("omits the named root key only, never a nested one of the same name", () => {
    const kinds = statePathKinds({ cfg: { overs: 20 }, inner: { cfg: 1 } }, new Set(), new Set(["cfg"]));
    expect([...kinds.keys()].sort()).toEqual(["inner", "inner.cfg"]);
  });
});

describe("canonical rendering", () => {
  const base = (): SchemaSnapshot => ({
    snapshotVersion: 1,
    key: "demo",
    version: "1.0.0",
    generatedBy: "testkit/schema-snapshot.ts",
    configSchema: { type: "object", required: ["b", "a"], properties: { b: {}, a: {} } },
    eventSchema: { enum: ["z", "a", "m"] },
    state: { paths: { b: ["number"], a: ["string"] } },
  });

  it("sorts every object key, so property insertion order cannot move the bytes", () => {
    const text = renderSchemaSnapshot(base());
    expect(text.indexOf('"configSchema"')).toBeLessThan(text.indexOf('"eventSchema"'));
    expect(text.indexOf('"a": {}')).toBeLessThan(text.indexOf('"b": {}'));
  });

  it("sorts the two set-valued JSON Schema keywords, and nothing else", () => {
    const snapshot = base();
    snapshot.configSchema = { required: ["b", "a"], anyOf: [{ x: 1 }, { y: 2 }] };
    const text = renderSchemaSnapshot(snapshot);
    expect(text).toContain('"required": [\n      "a",\n      "b"\n    ]');
    // anyOf is positional — reordering it is a real change, so it is preserved.
    expect(text.indexOf('"x"')).toBeLessThan(text.indexOf('"y"'));
  });

  it("is byte-identical when the same snapshot is rendered twice", () => {
    expect(renderSchemaSnapshot(base())).toBe(renderSchemaSnapshot(base()));
  });

  it("is 2-space pretty-printed and newline-terminated", () => {
    const text = renderSchemaSnapshot(base());
    expect(text.endsWith("}\n")).toBe(true);
    expect(text).toContain('\n  "key": "demo"');
  });

  it("regenerates every real module byte-identically", () => {
    // The CI gate is `regenerate; git status --porcelain` — if a rebuild of the
    // same module could differ from itself, that gate would red at random.
    for (const module of builtinModules) {
      const again = buildSchemaSnapshot(module);
      expect(renderSchemaSnapshot(again)).toBe(renderSchemaSnapshot(snapshotFor(module.key)));
    }
  });
});

describe("staleness report", () => {
  it("names a dropped enum member on ONE line, not as a re-indexing cascade", () => {
    const before = { configSchema: { properties: { mode: { enum: ["indoor", "beach", "grass"] } } } };
    const after = { configSchema: { properties: { mode: { enum: ["indoor", "grass"] } } } };
    const lines = formatSnapshotChanges(snapshotChanges(before, after));
    expect(lines).toEqual(['  - configSchema.properties.mode.enum: removed "beach"']);
  });

  it("reports a removed property, an added one and a changed leaf distinctly", () => {
    const changes = snapshotChanges(
      { a: 1, gone: true, deep: { n: 1 } },
      { a: 2, added: "x", deep: { n: 1 } },
    );
    expect(changes.map((c) => `${c.kind} ${c.path}`).sort()).toEqual([
      "added added",
      "changed a",
      "removed gone",
    ]);
  });

  it("counts the removals, because a removal is the narrowing", () => {
    const report = stalenessReport(
      "demo",
      JSON.stringify({ state: { paths: { a: ["number"], b: ["string"] } } }),
      JSON.stringify({ state: { paths: { a: ["number"] } } }),
    );
    expect(report).toContain("STALE");
    expect(report).toContain("1 change(s), 1 of them REMOVALS");
    expect(report).toContain("state.paths.b");
    expect(report).toContain("schema:snapshot");
  });

  it("says MISSING rather than diffing against nothing", () => {
    expect(stalenessReport("demo", null, "{}\n")).toContain("MISSING");
  });

  it("distinguishes a rendering-rule change from a schema change", () => {
    const report = stalenessReport("demo", '{"a":1}', '{\n  "a": 1\n}\n');
    expect(report).toContain("structurally identical");
  });

  it("returns the empty string when the bytes are current", () => {
    expect(stalenessReport("demo", "{}\n", "{}\n")).toBe("");
  });

  it("caps the printed change list rather than dumping the whole file", () => {
    const before: Record<string, number> = {};
    for (let i = 0; i < 60; i++) before[`k${String(i).padStart(2, "0")}`] = i;
    const lines = formatSnapshotChanges(snapshotChanges(before, {}));
    expect(lines.length).toBe(41);
    expect(lines[40]).toBe("  … 20 more");
  });
});
